# Generated by Django 5.1.1 on 2025-03-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
